
# https://jupyterbook.org/en/stable/publish/gh-pages.html

name: quarto-pages

on:
  push:
    branches:
    - main
    # run only if a file within that specific folder has been modified:
    #paths:
    #- docs/**

  # make this workflow manually runnable
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:


jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    #
    # PYTHON STUFF
    #

    # INSTALL PYTHON
    #- name: Set up Python 3.11
    #  uses: actions/setup-python@v4
    #  with:
    #    python-version: 3.11

    ## INSTALL PACKAGE DEPENDENCIES (IF YOU ARE DOCUMENTING YOUR PACKAGE)
    #- name: Install dependencies
    #  run: |
    #    pip install -r requirements.txt

    # INSTALL DOCUMENTATION DEPENDENCIES
    #- name: Install docs dependencies
    #  run: |
    #    pip install -r docs/requirements.txt

    #
    # QUARTO STUFF
    #

    # INSTALL QUARTO
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      #env:
      #  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # To install LaTeX to build PDF book
        # (to get past errors on the CI build)
        tinytex: true
        # uncomment below and fill to pin a version
        # version: SPECIFIC-QUARTO-VERSION-HERE

    # SAVE AS HTML (SEE docs/_build OR docs/_book)
    - name: Build the book
      run: |
        quarto render docs/

    #
    # GITHUB PAGES STUFF
    #

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "docs/_build"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
